{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGODB_URI: {{ .Values.secret.mongodbUri | b64enc | quote }}
  SECRET_KEY: {{ .Values.secret.secretKey | b64enc | quote }}
{{- end }}
