apiVersion: v1
kind: Service
metadata:
  name: webapp-lb
spec:
  type: {{ .Values.service.type }}
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
